#!/usr/bin/env bash
#
# Copyright (C) 2023 FortuneOS
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

# Telegran setup
echo "TELEGRAM_TOKEN=$TG_TOKEN
TELEGRAM_CHAT=$TG_CHAT" > ~/.telegram.sh
wget https://raw.githubusercontent.com/Hopireika/telegram.sh/master/telegram
chmod a+x telegram
TELEGRAM="$(pwd)/telegram"
message() {
	"${TELEGRAM}" -H -D \
		-i "banner/fortune.jpg" \
		"$(
                        for POST in "${@}"; do
                                echo "${POST}"
                        done
                )"
}

device="$1"
wget https://raw.githubusercontent.com/Fortune-OS/official-keepers/13.0/device/$device.json
device_name=$(grep -o '"device_name": "[^"]*' $device.json | grep -o '[^"]*$')
filename=$(grep -o '"filename": "[^"]*' $device.json | grep -o '[^"]*$')
link="https://www.pling.com/p/2066862"
build_date=$(date "+%d%m%Y")
sha256sum=$(grep -o '"id": "[^"]*' $device.json | grep -o '[^"]*$')
maintainer=$(grep -o '"maintainer": "[^"]*' $device.json | grep -o '[^"]*$')
version=$(grep -o '"version": "[^"]*' $device.json | grep -o '[^"]*$')
romtype=$(grep -o '"romtype": "[^"]*' $device.json | grep -o '[^"]*$')

message "
New build available for <b>$device</b>!
<b>By:</b> $maintainer

<b>Build date:</b> <code>$build_date</code>
<b>Device name:</b> <code>$device_name</code>
<b>Version:</b> <code>$version</code>
<b>File name:</b> <code>$filename</code>
<b>Buldtype:</b> <code>$romtype</code>
<b>SHA256:</b> <code>$sha256sum</code>

<b>Download:</b> <a href='$link'>Here!</a>

#fortune #letsfortune #keepfortune #$device"

rm $device.json
rm telegram
